---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# guttmacherggplottheme

<!-- badges: start -->
<!-- badges: end -->

The goal of guttmacherggplottheme is to provide ggplot themes and color palettes that align with Guttmacher's branding.

## Installation

You can install the development version of guttmacherggplottheme from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("GuttInst/guttmacherggplottheme")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(guttmacherggplottheme)
library(ggplot2)
library(ggthemes)
library(extrafont)

data(iris)

font_import(pattern="arial.ttf", prompt=FALSE)
loadfonts()

# Define color palettes
categorical_palette <- guttmacherggplottheme::get_categorical_palette(4)
sequential_palette <- guttmacherggplottheme::get_sequential_palette("violet")
divergent_palette <- guttmacherggplottheme::get_divergent_palette() 

# Test plot with categorical palette
ggplot2::ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  geom_point() + labs (title ="Floral Test Plot (Categorical)" )  + 
  scale_color_manual(values = categorical_palette) + # Use categorial palette here
  guttmacherggplottheme::guttmacher_theme()

# Test plot with sequential palette
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Petal.Length)) +
  geom_point() + scale_color_gradientn(colors = sequential_palette) + # Use sequential palette here
  guttmacherggplottheme::guttmacher_theme() +
  labs(title = "Floral Test Plot (Sequential)") 

# Test plot with divergent palette 
divergent_palette <- guttmacherggplottheme::get_divergent_palette() 
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Petal.Length)) +
  geom_point() + scale_color_gradientn(colors = divergent_palette) + # Use divergent palette here
  guttmacherggplottheme::guttmacher_theme() +
  labs(title = "Floral Test Plot (Divergent)") 


```
